# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "254c161a5700fcb0582c9e745ca2edb0"
name = "vibra-cart"
handle = "vibra-cart"
application_url = "https://societies-disagree-photographers-alerts.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tayyab-products.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://societies-disagree-photographers-alerts.trycloudflare.com/auth/callback",
  "https://societies-disagree-photographers-alerts.trycloudflare.com/auth/shopify/callback",
  "https://societies-disagree-photographers-alerts.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
